[manifest]
summary = "MeshJS off-chain project with a transaction building example"

[[files]]
source = "package.json.jinja"
dest = "package.json"

[[files]]
source = "Justfile.jinja"
dest = "Justfile"

[[files]]
source = "src/index.ts"
dest = "src/index.ts"
